ARDUINO_DIR  = ../../../../arduino-1.6.13
USER_LIB_PATH = ../../../../ardulibs
ARDUINO_LIBS = SPI MySensors-2.0
BOARD_TAG    = nano
BOARD_SUB    = atmega328
MONITOR_PORT = /dev/ttyUSB1
include ../../../../Arduino-Makefile-1.5.1/Arduino.mk
